### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/seneca_dialogues_aubrey-stewart#7]
https://github.com/standardebooks/seneca_dialogues_aubrey-stewart/blob/3a57bbc72ca10d00ac6f3706f5278693b6b436a9/src/epub/text/on-anger.xhtml#L305C586-L305C699

"Finally, the other passions seize upon individuals anger is the only one which sometimes possesses a whole state."

A semi-colon is missing between "individuals" and "anger".

**Comment by acabal** [comment]
Thanks, this is fixed now!
